"""empty message

Revision ID: 1963f9a6fb4f
Revises: b01089511dc6
Create Date: 2025-09-12 17:28:14.827473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1963f9a6fb4f'
down_revision = 'b01089511dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('username_required')

    # ### end Alembic commands ###
