"""empty message

Revision ID: 7381166d4898
Revises: 1c8bc4a7c604
Create Date: 2025-08-12 09:50:52.695365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7381166d4898'
down_revision = '1c8bc4a7c604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fingerprint', sa.String(), nullable=False))
        batch_op.drop_column('ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('fingerprint')
        batch_op.drop_column('ip_hash')

    # ### end Alembic commands ###
