"""empty message

Revision ID: 885edf2f180d
Revises: 9f2478c54b33
Create Date: 2025-08-13 12:24:59.345734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885edf2f180d'
down_revision = '9f2478c54b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed', sa.Boolean(), nullable=False))
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('choice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('failed')

    # ### end Alembic commands ###
