"""empty message

Revision ID: 982886ec89fc
Revises: 7381166d4898
Create Date: 2025-08-12 10:04:41.263671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982886ec89fc'
down_revision = '7381166d4898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
