"""empty message

Revision ID: 9f2478c54b33
Revises: 982886ec89fc
Create Date: 2025-08-12 10:07:54.901334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2478c54b33'
down_revision = '982886ec89fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
